name: RokiDragon
main: com.youssgm3o8.rokidragon.DragonPlugin
version: 1.0.0
api: ["1.0.0"]
author: YoussGm3o8

commands:
  dragonmanage:
    description: Open the dragon management GUI
    usage: /dragonmanage
    aliases: [dm, dragongui]
    permission: rokidragon.command.manage
  summondragon:
    description: Summon your dragon
    usage: /summondragon [buy|lost|admin <player>]
    aliases: [dragon, drg]
    permission: rokidragon.command.summon

permissions:
  rokidragon.command.manage:
    description: Allows using the dragon management command
    default: true
  rokidragon.command.summon:
    description: Allows summoning a dragon
    default: true